---
version: "3"

tasks:
  default:
    cmds:
      - goimports -w .
      - go mod tidy
      - go fmt ./...
      - task: install
      - task: test

  install: go install ./cmd/...

  test:
    cmds:
      - go test -v ./...

  record:
    cmds:
      - task: install
      - rm -f atkins_demo.cast atkins_demo.gif
      - asciinema rec -t "Atkins CI runner example" -c "task run" atkins_demo.cast
      - $HOME/.cargo/bin/agg atkins_demo.cast atkins_demo.gif

  run:
    cmds:
      - atkins -file test/pipelines/atkins.yml

  run:error:
    cmds:
      - atkins -file test/pipelines/atkins-err.yml
