#!/usr/bin/env atkins
name: Generate atkins example screenshots

when:
  files:
    - $(which termos)

vars:
  semver: $(git tag | tail -n 1)
  image: titpetric/atkins
  build:
    goarch: [arm64, amd64]
  tests: ["detach", "depends_on", "root_jobs"]

env:
  vars:
    CI: "true"

jobs:
  default:
    depends_on:
      - main
      - run
      - list
    steps:
      - rm examples/*.txt

  main:
    tty: true
    detach: true
    steps:
      - termos shot -c 120 --filename examples/atkins.run -- atkins --final
      - termos shot -c 120 --filename examples/atkins.list -- atkins -l

  run:
    tty: true
    detach: true
    steps:
      - for: test in tests
        cmd: termos shot -c 120 --filename examples/${{test}}.run -- atkins --file tests/${{test}}.yml --final

  list:
    tty: true
    detach: true
    steps:
      - for: test in tests
        cmd: termos shot -c 120 --filename examples/${{test}}.list -- atkins -l --file tests/${{test}}.yml
