package model

// Code generated by go-bridget/mig. DO NOT EDIT.

import (
	"fmt"
	"strings"
	"time"
)

// QueryOption is implemented by each data model type.
type QueryOption interface {
	WithTable(name string) QueryOption
	WithColumns(cols []string) QueryOption
	WithWhere(clause string) QueryOption
	WithOrderBy(clause string) QueryOption
	WithLimit(start, offset int) QueryOption
	WithStatement(stmt string) QueryOption
}

// QueryConfig is a function-chaining SQL statement type.
type QueryConfig struct {
	Table       string
	Columns     []string
	Where       string
	OrderBy     string
	LimitStart  int
	LimitOffset int
	Statement   string
}

// WithTable will set the table name for the query.
func (q *QueryConfig) WithTable(name string) QueryOption {
	q.Table = name
	return q
}

// WithColumns will set the columns to use for the query.
func (q *QueryConfig) WithColumns(cols []string) QueryOption {
	q.Columns = cols
	return q
}

// WithWhere will set the where condition for the query.
func (q *QueryConfig) WithWhere(clause string) QueryOption {
	q.Where = clause
	return q
}

// WithOrderBy will set the order by clause for the query.
func (q *QueryConfig) WithOrderBy(clause string) QueryOption {
	q.OrderBy = clause
	return q
}

// WithLimit will set the limit clause parameters for the query.
func (q *QueryConfig) WithLimit(start, offset int) QueryOption {
	q.LimitStart = start
	q.LimitOffset = offset
	return q
}

// WithStatement will change the statement for the query.
func (q *QueryConfig) WithStatement(stmt string) QueryOption {
	q.Statement = stmt
	return q
}

// WithTable will set the table name for the query.
func WithTable(name string) QueryOption {
	return &QueryConfig{Table: name}
}

// WithColumns will set the columns to use for the query.
func WithColumns(cols []string) QueryOption {
	return &QueryConfig{Columns: cols}
}

// WithWhere will set the where condition for the query.
func WithWhere(clause string) QueryOption {
	return &QueryConfig{Where: clause}
}

// WithOrderBy will set the order by clause for the query.
func WithOrderBy(clause string) QueryOption {
	return &QueryConfig{OrderBy: clause}
}

// WithLimit will set the limit clause parameters for the query.
func WithLimit(start, offset int) QueryOption {
	return &QueryConfig{LimitStart: start, LimitOffset: offset}
}

// WithStatement will change the statement for the query.
func WithStatement(stmt string) QueryOption {
	return &QueryConfig{Statement: stmt}
}

// Apply will use passed query options to populate the query.
func (q *QueryConfig) Apply(opts ...QueryOption) *QueryConfig {
	cfg := *q
	for _, opt := range opts {
		o := opt.(*QueryConfig)
		if o.Table != "" {
			cfg.Table = o.Table
		}
		if len(o.Columns) > 0 {
			cfg.Columns = o.Columns
		}
		if o.Where != "" {
			cfg.Where = o.Where
		}
		if o.OrderBy != "" {
			cfg.OrderBy = o.OrderBy
		}
		if o.LimitOffset > 0 {
			cfg.LimitStart = o.LimitStart
			cfg.LimitOffset = o.LimitOffset
		}
		if o.Statement != "" {
			cfg.Statement = o.Statement
		}
	}
	return &cfg
}

// Job generated for db table `job`.
type Job struct {
	// ID
	ID string `db:"id" json:"id"`

	// Parent ID
	ParentID string `db:"parent_id" json:"parent_id"`

	// Root ID
	RootID string `db:"root_id" json:"root_id"`

	// Depth
	Depth int64 `db:"depth" json:"depth"`

	// Repository ID
	RepositoryID string `db:"repository_id" json:"repository_id"`

	// User ID
	UserID string `db:"user_id" json:"user_id"`

	// Working Directory
	WorkingDirectory string `db:"working_directory" json:"working_directory"`

	// Command
	Command string `db:"command" json:"command"`

	// Branch
	Branch string `db:"branch" json:"branch"`

	// Revision
	Revision string `db:"revision" json:"revision"`

	// Labels
	Labels string `db:"labels" json:"labels"`

	// Params
	Params string `db:"params" json:"params"`

	// Status
	Status string `db:"status" json:"status"`

	// Exit Code
	ExitCode int64 `db:"exit_code" json:"exit_code"`

	// Error
	Error string `db:"error" json:"error"`

	// Agent ID
	AgentID string `db:"agent_id" json:"agent_id"`

	// Lease Expires At
	LeaseExpiresAt *time.Time `db:"lease_expires_at" json:"lease_expires_at"`

	// Started At
	StartedAt *time.Time `db:"started_at" json:"started_at"`

	// Finished At
	FinishedAt *time.Time `db:"finished_at" json:"finished_at"`

	// Created At
	CreatedAt *time.Time `db:"created_at" json:"created_at"`

	// Updated At
	UpdatedAt *time.Time `db:"updated_at" json:"updated_at"`
}

// GetID will return the value of ID.
func (j *Job) GetID() string { return j.ID }

// SetID sets ID to the provided value.
func (j *Job) SetID(val string) { j.ID = val }

// GetParentID will return the value of ParentID.
func (j *Job) GetParentID() string { return j.ParentID }

// SetParentID sets ParentID to the provided value.
func (j *Job) SetParentID(val string) { j.ParentID = val }

// GetRootID will return the value of RootID.
func (j *Job) GetRootID() string { return j.RootID }

// SetRootID sets RootID to the provided value.
func (j *Job) SetRootID(val string) { j.RootID = val }

// GetDepth will return the value of Depth.
func (j *Job) GetDepth() int64 { return j.Depth }

// SetDepth sets Depth to the provided value.
func (j *Job) SetDepth(val int64) { j.Depth = val }

// GetRepositoryID will return the value of RepositoryID.
func (j *Job) GetRepositoryID() string { return j.RepositoryID }

// SetRepositoryID sets RepositoryID to the provided value.
func (j *Job) SetRepositoryID(val string) { j.RepositoryID = val }

// GetUserID will return the value of UserID.
func (j *Job) GetUserID() string { return j.UserID }

// SetUserID sets UserID to the provided value.
func (j *Job) SetUserID(val string) { j.UserID = val }

// GetWorkingDirectory will return the value of WorkingDirectory.
func (j *Job) GetWorkingDirectory() string { return j.WorkingDirectory }

// SetWorkingDirectory sets WorkingDirectory to the provided value.
func (j *Job) SetWorkingDirectory(val string) { j.WorkingDirectory = val }

// GetCommand will return the value of Command.
func (j *Job) GetCommand() string { return j.Command }

// SetCommand sets Command to the provided value.
func (j *Job) SetCommand(val string) { j.Command = val }

// GetBranch will return the value of Branch.
func (j *Job) GetBranch() string { return j.Branch }

// SetBranch sets Branch to the provided value.
func (j *Job) SetBranch(val string) { j.Branch = val }

// GetRevision will return the value of Revision.
func (j *Job) GetRevision() string { return j.Revision }

// SetRevision sets Revision to the provided value.
func (j *Job) SetRevision(val string) { j.Revision = val }

// GetLabels will return the value of Labels.
func (j *Job) GetLabels() string { return j.Labels }

// SetLabels sets Labels to the provided value.
func (j *Job) SetLabels(val string) { j.Labels = val }

// GetParams will return the value of Params.
func (j *Job) GetParams() string { return j.Params }

// SetParams sets Params to the provided value.
func (j *Job) SetParams(val string) { j.Params = val }

// GetStatus will return the value of Status.
func (j *Job) GetStatus() string { return j.Status }

// SetStatus sets Status to the provided value.
func (j *Job) SetStatus(val string) { j.Status = val }

// GetExitCode will return the value of ExitCode.
func (j *Job) GetExitCode() int64 { return j.ExitCode }

// SetExitCode sets ExitCode to the provided value.
func (j *Job) SetExitCode(val int64) { j.ExitCode = val }

// GetError will return the value of Error.
func (j *Job) GetError() string { return j.Error }

// SetError sets Error to the provided value.
func (j *Job) SetError(val string) { j.Error = val }

// GetAgentID will return the value of AgentID.
func (j *Job) GetAgentID() string { return j.AgentID }

// SetAgentID sets AgentID to the provided value.
func (j *Job) SetAgentID(val string) { j.AgentID = val }

// GetLeaseExpiresAt will return the value of LeaseExpiresAt.
func (j *Job) GetLeaseExpiresAt() *time.Time { return j.LeaseExpiresAt }

// SetLeaseExpiresAt sets LeaseExpiresAt to the provided value.
func (j *Job) SetLeaseExpiresAt(stamp time.Time) { j.LeaseExpiresAt = &stamp }

// GetStartedAt will return the value of StartedAt.
func (j *Job) GetStartedAt() *time.Time { return j.StartedAt }

// SetStartedAt sets StartedAt to the provided value.
func (j *Job) SetStartedAt(stamp time.Time) { j.StartedAt = &stamp }

// GetFinishedAt will return the value of FinishedAt.
func (j *Job) GetFinishedAt() *time.Time { return j.FinishedAt }

// SetFinishedAt sets FinishedAt to the provided value.
func (j *Job) SetFinishedAt(stamp time.Time) { j.FinishedAt = &stamp }

// GetCreatedAt will return the value of CreatedAt.
func (j *Job) GetCreatedAt() *time.Time { return j.CreatedAt }

// SetCreatedAt sets CreatedAt to the provided value.
func (j *Job) SetCreatedAt(stamp time.Time) { j.CreatedAt = &stamp }

// GetUpdatedAt will return the value of UpdatedAt.
func (j *Job) GetUpdatedAt() *time.Time { return j.UpdatedAt }

// SetUpdatedAt sets UpdatedAt to the provided value.
func (j *Job) SetUpdatedAt(stamp time.Time) { j.UpdatedAt = &stamp }

// JobTable is the name of the table in the DB.
const JobTable = "`job`"

// JobFields is a list of all columns in the DB table.
var JobFields = []string{"id", "parent_id", "root_id", "depth", "repository_id", "user_id", "working_directory", "command", "branch", "revision", "labels", "params", "status", "exit_code", "error", "agent_id", "lease_expires_at", "started_at", "finished_at", "created_at", "updated_at"}

// JobPrimaryFields are the primary key fields in the DB table.
var JobPrimaryFields = []string{"id"}

// JobLog generated for db table `job_log`.
//
// Job Log.
type JobLog struct {
	// ID
	ID string `db:"id" json:"id"`

	// Job ID
	JobID string `db:"job_id" json:"job_id"`

	// Seq
	Seq int64 `db:"seq" json:"seq"`

	// Stream
	Stream string `db:"stream" json:"stream"`

	// Content
	Content string `db:"content" json:"content"`

	// Created At
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
}

// GetID will return the value of ID.
func (j *JobLog) GetID() string { return j.ID }

// SetID sets ID to the provided value.
func (j *JobLog) SetID(val string) { j.ID = val }

// GetJobID will return the value of JobID.
func (j *JobLog) GetJobID() string { return j.JobID }

// SetJobID sets JobID to the provided value.
func (j *JobLog) SetJobID(val string) { j.JobID = val }

// GetSeq will return the value of Seq.
func (j *JobLog) GetSeq() int64 { return j.Seq }

// SetSeq sets Seq to the provided value.
func (j *JobLog) SetSeq(val int64) { j.Seq = val }

// GetStream will return the value of Stream.
func (j *JobLog) GetStream() string { return j.Stream }

// SetStream sets Stream to the provided value.
func (j *JobLog) SetStream(val string) { j.Stream = val }

// GetContent will return the value of Content.
func (j *JobLog) GetContent() string { return j.Content }

// SetContent sets Content to the provided value.
func (j *JobLog) SetContent(val string) { j.Content = val }

// GetCreatedAt will return the value of CreatedAt.
func (j *JobLog) GetCreatedAt() *time.Time { return j.CreatedAt }

// SetCreatedAt sets CreatedAt to the provided value.
func (j *JobLog) SetCreatedAt(stamp time.Time) { j.CreatedAt = &stamp }

// JobLogTable is the name of the table in the DB.
const JobLogTable = "`job_log`"

// JobLogFields is a list of all columns in the DB table.
var JobLogFields = []string{"id", "job_id", "seq", "stream", "content", "created_at"}

// JobLogPrimaryFields are the primary key fields in the DB table.
var JobLogPrimaryFields = []string{"id"}

// Migrations generated for db table `migrations`.
type Migrations struct {
	// Project
	Project string `db:"project" json:"project"`

	// Filename
	Filename string `db:"filename" json:"filename"`

	// Statement Index
	StatementIndex int64 `db:"statement_index" json:"statement_index"`

	// Status
	Status string `db:"status" json:"status"`
}

// GetProject will return the value of Project.
func (m *Migrations) GetProject() string { return m.Project }

// SetProject sets Project to the provided value.
func (m *Migrations) SetProject(val string) { m.Project = val }

// GetFilename will return the value of Filename.
func (m *Migrations) GetFilename() string { return m.Filename }

// SetFilename sets Filename to the provided value.
func (m *Migrations) SetFilename(val string) { m.Filename = val }

// GetStatementIndex will return the value of StatementIndex.
func (m *Migrations) GetStatementIndex() int64 { return m.StatementIndex }

// SetStatementIndex sets StatementIndex to the provided value.
func (m *Migrations) SetStatementIndex(val int64) { m.StatementIndex = val }

// GetStatus will return the value of Status.
func (m *Migrations) GetStatus() string { return m.Status }

// SetStatus sets Status to the provided value.
func (m *Migrations) SetStatus(val string) { m.Status = val }

// MigrationsTable is the name of the table in the DB.
const MigrationsTable = "`migrations`"

// MigrationsFields is a list of all columns in the DB table.
var MigrationsFields = []string{"project", "filename", "statement_index", "status"}

// MigrationsPrimaryFields are the primary key fields in the DB table.
var MigrationsPrimaryFields = []string{"project", "filename"}

// Repository generated for db table `repository`.
type Repository struct {
	// ID
	ID string `db:"id" json:"id"`

	// Slug
	Slug string `db:"slug" json:"slug"`

	// Remote URL
	RemoteURL string `db:"remote_url" json:"remote_url"`

	// Default Branch
	DefaultBranch string `db:"default_branch" json:"default_branch"`

	// Created By User ID
	CreatedByUserID string `db:"created_by_user_id" json:"created_by_user_id"`

	// Is Active
	IsActive bool `db:"is_active" json:"is_active"`

	// Created At
	CreatedAt *time.Time `db:"created_at" json:"created_at"`

	// Updated At
	UpdatedAt *time.Time `db:"updated_at" json:"updated_at"`

	// Deleted At
	DeletedAt *time.Time `db:"deleted_at" json:"deleted_at"`
}

// GetID will return the value of ID.
func (r *Repository) GetID() string { return r.ID }

// SetID sets ID to the provided value.
func (r *Repository) SetID(val string) { r.ID = val }

// GetSlug will return the value of Slug.
func (r *Repository) GetSlug() string { return r.Slug }

// SetSlug sets Slug to the provided value.
func (r *Repository) SetSlug(val string) { r.Slug = val }

// GetRemoteURL will return the value of RemoteURL.
func (r *Repository) GetRemoteURL() string { return r.RemoteURL }

// SetRemoteURL sets RemoteURL to the provided value.
func (r *Repository) SetRemoteURL(val string) { r.RemoteURL = val }

// GetDefaultBranch will return the value of DefaultBranch.
func (r *Repository) GetDefaultBranch() string { return r.DefaultBranch }

// SetDefaultBranch sets DefaultBranch to the provided value.
func (r *Repository) SetDefaultBranch(val string) { r.DefaultBranch = val }

// GetCreatedByUserID will return the value of CreatedByUserID.
func (r *Repository) GetCreatedByUserID() string { return r.CreatedByUserID }

// SetCreatedByUserID sets CreatedByUserID to the provided value.
func (r *Repository) SetCreatedByUserID(val string) { r.CreatedByUserID = val }

// GetIsActive will return the value of IsActive.
func (r *Repository) GetIsActive() bool { return r.IsActive }

// SetIsActive sets IsActive to the provided value.
func (r *Repository) SetIsActive(val bool) { r.IsActive = val }

// GetCreatedAt will return the value of CreatedAt.
func (r *Repository) GetCreatedAt() *time.Time { return r.CreatedAt }

// SetCreatedAt sets CreatedAt to the provided value.
func (r *Repository) SetCreatedAt(stamp time.Time) { r.CreatedAt = &stamp }

// GetUpdatedAt will return the value of UpdatedAt.
func (r *Repository) GetUpdatedAt() *time.Time { return r.UpdatedAt }

// SetUpdatedAt sets UpdatedAt to the provided value.
func (r *Repository) SetUpdatedAt(stamp time.Time) { r.UpdatedAt = &stamp }

// GetDeletedAt will return the value of DeletedAt.
func (r *Repository) GetDeletedAt() *time.Time { return r.DeletedAt }

// SetDeletedAt sets DeletedAt to the provided value.
func (r *Repository) SetDeletedAt(stamp time.Time) { r.DeletedAt = &stamp }

// RepositoryTable is the name of the table in the DB.
const RepositoryTable = "`repository`"

// RepositoryFields is a list of all columns in the DB table.
var RepositoryFields = []string{"id", "slug", "remote_url", "default_branch", "created_by_user_id", "is_active", "created_at", "updated_at", "deleted_at"}

// RepositoryPrimaryFields are the primary key fields in the DB table.
var RepositoryPrimaryFields = []string{"id"}

// RepositoryRule generated for db table `repository_rule`.
//
// Repository Rule.
type RepositoryRule struct {
	// ID
	ID string `db:"id" json:"id"`

	// Pattern
	Pattern string `db:"pattern" json:"pattern"`

	// Description
	Description string `db:"description" json:"description"`

	// Is Active
	IsActive bool `db:"is_active" json:"is_active"`

	// Created By User ID
	CreatedByUserID string `db:"created_by_user_id" json:"created_by_user_id"`

	// Created At
	CreatedAt *time.Time `db:"created_at" json:"created_at"`

	// Updated At
	UpdatedAt *time.Time `db:"updated_at" json:"updated_at"`

	// Deleted At
	DeletedAt *time.Time `db:"deleted_at" json:"deleted_at"`
}

// GetID will return the value of ID.
func (r *RepositoryRule) GetID() string { return r.ID }

// SetID sets ID to the provided value.
func (r *RepositoryRule) SetID(val string) { r.ID = val }

// GetPattern will return the value of Pattern.
func (r *RepositoryRule) GetPattern() string { return r.Pattern }

// SetPattern sets Pattern to the provided value.
func (r *RepositoryRule) SetPattern(val string) { r.Pattern = val }

// GetDescription will return the value of Description.
func (r *RepositoryRule) GetDescription() string { return r.Description }

// SetDescription sets Description to the provided value.
func (r *RepositoryRule) SetDescription(val string) { r.Description = val }

// GetIsActive will return the value of IsActive.
func (r *RepositoryRule) GetIsActive() bool { return r.IsActive }

// SetIsActive sets IsActive to the provided value.
func (r *RepositoryRule) SetIsActive(val bool) { r.IsActive = val }

// GetCreatedByUserID will return the value of CreatedByUserID.
func (r *RepositoryRule) GetCreatedByUserID() string { return r.CreatedByUserID }

// SetCreatedByUserID sets CreatedByUserID to the provided value.
func (r *RepositoryRule) SetCreatedByUserID(val string) { r.CreatedByUserID = val }

// GetCreatedAt will return the value of CreatedAt.
func (r *RepositoryRule) GetCreatedAt() *time.Time { return r.CreatedAt }

// SetCreatedAt sets CreatedAt to the provided value.
func (r *RepositoryRule) SetCreatedAt(stamp time.Time) { r.CreatedAt = &stamp }

// GetUpdatedAt will return the value of UpdatedAt.
func (r *RepositoryRule) GetUpdatedAt() *time.Time { return r.UpdatedAt }

// SetUpdatedAt sets UpdatedAt to the provided value.
func (r *RepositoryRule) SetUpdatedAt(stamp time.Time) { r.UpdatedAt = &stamp }

// GetDeletedAt will return the value of DeletedAt.
func (r *RepositoryRule) GetDeletedAt() *time.Time { return r.DeletedAt }

// SetDeletedAt sets DeletedAt to the provided value.
func (r *RepositoryRule) SetDeletedAt(stamp time.Time) { r.DeletedAt = &stamp }

// RepositoryRuleTable is the name of the table in the DB.
const RepositoryRuleTable = "`repository_rule`"

// RepositoryRuleFields is a list of all columns in the DB table.
var RepositoryRuleFields = []string{"id", "pattern", "description", "is_active", "created_by_user_id", "created_at", "updated_at", "deleted_at"}

// RepositoryRulePrimaryFields are the primary key fields in the DB table.
var RepositoryRulePrimaryFields = []string{"id"}

// Session generated for db table `session`.
type Session struct {
	// ID
	ID string `db:"id" json:"id"`

	// User ID
	UserID string `db:"user_id" json:"user_id"`

	// Refresh Token
	RefreshToken string `db:"refresh_token" json:"refresh_token"`

	// Hostname
	Hostname string `db:"hostname" json:"hostname"`

	// User Agent
	UserAgent string `db:"user_agent" json:"user_agent"`

	// Remote Addr
	RemoteAddr string `db:"remote_addr" json:"remote_addr"`

	// Last Seen At
	LastSeenAt *time.Time `db:"last_seen_at" json:"last_seen_at"`

	// Expires At
	ExpiresAt *time.Time `db:"expires_at" json:"expires_at"`

	// Revoked At
	RevokedAt *time.Time `db:"revoked_at" json:"revoked_at"`

	// Created At
	CreatedAt *time.Time `db:"created_at" json:"created_at"`

	// Updated At
	UpdatedAt *time.Time `db:"updated_at" json:"updated_at"`
}

// GetID will return the value of ID.
func (s *Session) GetID() string { return s.ID }

// SetID sets ID to the provided value.
func (s *Session) SetID(val string) { s.ID = val }

// GetUserID will return the value of UserID.
func (s *Session) GetUserID() string { return s.UserID }

// SetUserID sets UserID to the provided value.
func (s *Session) SetUserID(val string) { s.UserID = val }

// GetRefreshToken will return the value of RefreshToken.
func (s *Session) GetRefreshToken() string { return s.RefreshToken }

// SetRefreshToken sets RefreshToken to the provided value.
func (s *Session) SetRefreshToken(val string) { s.RefreshToken = val }

// GetHostname will return the value of Hostname.
func (s *Session) GetHostname() string { return s.Hostname }

// SetHostname sets Hostname to the provided value.
func (s *Session) SetHostname(val string) { s.Hostname = val }

// GetUserAgent will return the value of UserAgent.
func (s *Session) GetUserAgent() string { return s.UserAgent }

// SetUserAgent sets UserAgent to the provided value.
func (s *Session) SetUserAgent(val string) { s.UserAgent = val }

// GetRemoteAddr will return the value of RemoteAddr.
func (s *Session) GetRemoteAddr() string { return s.RemoteAddr }

// SetRemoteAddr sets RemoteAddr to the provided value.
func (s *Session) SetRemoteAddr(val string) { s.RemoteAddr = val }

// GetLastSeenAt will return the value of LastSeenAt.
func (s *Session) GetLastSeenAt() *time.Time { return s.LastSeenAt }

// SetLastSeenAt sets LastSeenAt to the provided value.
func (s *Session) SetLastSeenAt(stamp time.Time) { s.LastSeenAt = &stamp }

// GetExpiresAt will return the value of ExpiresAt.
func (s *Session) GetExpiresAt() *time.Time { return s.ExpiresAt }

// SetExpiresAt sets ExpiresAt to the provided value.
func (s *Session) SetExpiresAt(stamp time.Time) { s.ExpiresAt = &stamp }

// GetRevokedAt will return the value of RevokedAt.
func (s *Session) GetRevokedAt() *time.Time { return s.RevokedAt }

// SetRevokedAt sets RevokedAt to the provided value.
func (s *Session) SetRevokedAt(stamp time.Time) { s.RevokedAt = &stamp }

// GetCreatedAt will return the value of CreatedAt.
func (s *Session) GetCreatedAt() *time.Time { return s.CreatedAt }

// SetCreatedAt sets CreatedAt to the provided value.
func (s *Session) SetCreatedAt(stamp time.Time) { s.CreatedAt = &stamp }

// GetUpdatedAt will return the value of UpdatedAt.
func (s *Session) GetUpdatedAt() *time.Time { return s.UpdatedAt }

// SetUpdatedAt sets UpdatedAt to the provided value.
func (s *Session) SetUpdatedAt(stamp time.Time) { s.UpdatedAt = &stamp }

// SessionTable is the name of the table in the DB.
const SessionTable = "`session`"

// SessionFields is a list of all columns in the DB table.
var SessionFields = []string{"id", "user_id", "refresh_token", "hostname", "user_agent", "remote_addr", "last_seen_at", "expires_at", "revoked_at", "created_at", "updated_at"}

// SessionPrimaryFields are the primary key fields in the DB table.
var SessionPrimaryFields = []string{"id"}

// Setting generated for db table `setting`.
type Setting struct {
	// Name
	Name string `db:"name" json:"name"`

	// Value
	Value string `db:"value" json:"value"`

	// Updated By User ID
	UpdatedByUserID string `db:"updated_by_user_id" json:"updated_by_user_id"`

	// Created At
	CreatedAt *time.Time `db:"created_at" json:"created_at"`

	// Updated At
	UpdatedAt *time.Time `db:"updated_at" json:"updated_at"`
}

// GetName will return the value of Name.
func (s *Setting) GetName() string { return s.Name }

// SetName sets Name to the provided value.
func (s *Setting) SetName(val string) { s.Name = val }

// GetValue will return the value of Value.
func (s *Setting) GetValue() string { return s.Value }

// SetValue sets Value to the provided value.
func (s *Setting) SetValue(val string) { s.Value = val }

// GetUpdatedByUserID will return the value of UpdatedByUserID.
func (s *Setting) GetUpdatedByUserID() string { return s.UpdatedByUserID }

// SetUpdatedByUserID sets UpdatedByUserID to the provided value.
func (s *Setting) SetUpdatedByUserID(val string) { s.UpdatedByUserID = val }

// GetCreatedAt will return the value of CreatedAt.
func (s *Setting) GetCreatedAt() *time.Time { return s.CreatedAt }

// SetCreatedAt sets CreatedAt to the provided value.
func (s *Setting) SetCreatedAt(stamp time.Time) { s.CreatedAt = &stamp }

// GetUpdatedAt will return the value of UpdatedAt.
func (s *Setting) GetUpdatedAt() *time.Time { return s.UpdatedAt }

// SetUpdatedAt sets UpdatedAt to the provided value.
func (s *Setting) SetUpdatedAt(stamp time.Time) { s.UpdatedAt = &stamp }

// SettingTable is the name of the table in the DB.
const SettingTable = "`setting`"

// SettingFields is a list of all columns in the DB table.
var SettingFields = []string{"name", "value", "updated_by_user_id", "created_at", "updated_at"}

// SettingPrimaryFields are the primary key fields in the DB table.
var SettingPrimaryFields = []string{"name"}

// SSHKey generated for db table `ssh_key`.
//
// SSH Key.
type SSHKey struct {
	// ID
	ID string `db:"id" json:"id"`

	// Name
	Name string `db:"name" json:"name"`

	// Host
	Host string `db:"host" json:"host"`

	// Private Key
	PrivateKey string `db:"private_key" json:"private_key"`

	// Public Key
	PublicKey string `db:"public_key" json:"public_key"`

	// Fingerprint
	Fingerprint string `db:"fingerprint" json:"fingerprint"`

	// Known Hosts
	KnownHosts string `db:"known_hosts" json:"known_hosts"`

	// Is Active
	IsActive bool `db:"is_active" json:"is_active"`

	// Created By User ID
	CreatedByUserID string `db:"created_by_user_id" json:"created_by_user_id"`

	// Last Used At
	LastUsedAt *time.Time `db:"last_used_at" json:"last_used_at"`

	// Created At
	CreatedAt *time.Time `db:"created_at" json:"created_at"`

	// Updated At
	UpdatedAt *time.Time `db:"updated_at" json:"updated_at"`

	// Deleted At
	DeletedAt *time.Time `db:"deleted_at" json:"deleted_at"`
}

// GetID will return the value of ID.
func (s *SSHKey) GetID() string { return s.ID }

// SetID sets ID to the provided value.
func (s *SSHKey) SetID(val string) { s.ID = val }

// GetName will return the value of Name.
func (s *SSHKey) GetName() string { return s.Name }

// SetName sets Name to the provided value.
func (s *SSHKey) SetName(val string) { s.Name = val }

// GetHost will return the value of Host.
func (s *SSHKey) GetHost() string { return s.Host }

// SetHost sets Host to the provided value.
func (s *SSHKey) SetHost(val string) { s.Host = val }

// GetPrivateKey will return the value of PrivateKey.
func (s *SSHKey) GetPrivateKey() string { return s.PrivateKey }

// SetPrivateKey sets PrivateKey to the provided value.
func (s *SSHKey) SetPrivateKey(val string) { s.PrivateKey = val }

// GetPublicKey will return the value of PublicKey.
func (s *SSHKey) GetPublicKey() string { return s.PublicKey }

// SetPublicKey sets PublicKey to the provided value.
func (s *SSHKey) SetPublicKey(val string) { s.PublicKey = val }

// GetFingerprint will return the value of Fingerprint.
func (s *SSHKey) GetFingerprint() string { return s.Fingerprint }

// SetFingerprint sets Fingerprint to the provided value.
func (s *SSHKey) SetFingerprint(val string) { s.Fingerprint = val }

// GetKnownHosts will return the value of KnownHosts.
func (s *SSHKey) GetKnownHosts() string { return s.KnownHosts }

// SetKnownHosts sets KnownHosts to the provided value.
func (s *SSHKey) SetKnownHosts(val string) { s.KnownHosts = val }

// GetIsActive will return the value of IsActive.
func (s *SSHKey) GetIsActive() bool { return s.IsActive }

// SetIsActive sets IsActive to the provided value.
func (s *SSHKey) SetIsActive(val bool) { s.IsActive = val }

// GetCreatedByUserID will return the value of CreatedByUserID.
func (s *SSHKey) GetCreatedByUserID() string { return s.CreatedByUserID }

// SetCreatedByUserID sets CreatedByUserID to the provided value.
func (s *SSHKey) SetCreatedByUserID(val string) { s.CreatedByUserID = val }

// GetLastUsedAt will return the value of LastUsedAt.
func (s *SSHKey) GetLastUsedAt() *time.Time { return s.LastUsedAt }

// SetLastUsedAt sets LastUsedAt to the provided value.
func (s *SSHKey) SetLastUsedAt(stamp time.Time) { s.LastUsedAt = &stamp }

// GetCreatedAt will return the value of CreatedAt.
func (s *SSHKey) GetCreatedAt() *time.Time { return s.CreatedAt }

// SetCreatedAt sets CreatedAt to the provided value.
func (s *SSHKey) SetCreatedAt(stamp time.Time) { s.CreatedAt = &stamp }

// GetUpdatedAt will return the value of UpdatedAt.
func (s *SSHKey) GetUpdatedAt() *time.Time { return s.UpdatedAt }

// SetUpdatedAt sets UpdatedAt to the provided value.
func (s *SSHKey) SetUpdatedAt(stamp time.Time) { s.UpdatedAt = &stamp }

// GetDeletedAt will return the value of DeletedAt.
func (s *SSHKey) GetDeletedAt() *time.Time { return s.DeletedAt }

// SetDeletedAt sets DeletedAt to the provided value.
func (s *SSHKey) SetDeletedAt(stamp time.Time) { s.DeletedAt = &stamp }

// SSHKeyTable is the name of the table in the DB.
const SSHKeyTable = "`ssh_key`"

// SSHKeyFields is a list of all columns in the DB table.
var SSHKeyFields = []string{"id", "name", "host", "private_key", "public_key", "fingerprint", "known_hosts", "is_active", "created_by_user_id", "last_used_at", "created_at", "updated_at", "deleted_at"}

// SSHKeyPrimaryFields are the primary key fields in the DB table.
var SSHKeyPrimaryFields = []string{"id"}

// User generated for db table `user`.
type User struct {
	// ID
	ID string `db:"id" json:"id"`

	// Email
	Email string `db:"email" json:"email"`

	// Username
	Username string `db:"username" json:"username"`

	// Full Name
	FullName string `db:"full_name" json:"full_name"`

	// Password
	Password string `db:"password" json:"password"`

	// Is Admin
	IsAdmin bool `db:"is_admin" json:"is_admin"`

	// Is Active
	IsActive bool `db:"is_active" json:"is_active"`

	// Created At
	CreatedAt *time.Time `db:"created_at" json:"created_at"`

	// Updated At
	UpdatedAt *time.Time `db:"updated_at" json:"updated_at"`

	// Deleted At
	DeletedAt *time.Time `db:"deleted_at" json:"deleted_at"`

	// Is Agent
	IsAgent bool `db:"is_agent" json:"is_agent"`
}

// GetID will return the value of ID.
func (u *User) GetID() string { return u.ID }

// SetID sets ID to the provided value.
func (u *User) SetID(val string) { u.ID = val }

// GetEmail will return the value of Email.
func (u *User) GetEmail() string { return u.Email }

// SetEmail sets Email to the provided value.
func (u *User) SetEmail(val string) { u.Email = val }

// GetUsername will return the value of Username.
func (u *User) GetUsername() string { return u.Username }

// SetUsername sets Username to the provided value.
func (u *User) SetUsername(val string) { u.Username = val }

// GetFullName will return the value of FullName.
func (u *User) GetFullName() string { return u.FullName }

// SetFullName sets FullName to the provided value.
func (u *User) SetFullName(val string) { u.FullName = val }

// GetPassword will return the value of Password.
func (u *User) GetPassword() string { return u.Password }

// SetPassword sets Password to the provided value.
func (u *User) SetPassword(val string) { u.Password = val }

// GetIsAdmin will return the value of IsAdmin.
func (u *User) GetIsAdmin() bool { return u.IsAdmin }

// SetIsAdmin sets IsAdmin to the provided value.
func (u *User) SetIsAdmin(val bool) { u.IsAdmin = val }

// GetIsActive will return the value of IsActive.
func (u *User) GetIsActive() bool { return u.IsActive }

// SetIsActive sets IsActive to the provided value.
func (u *User) SetIsActive(val bool) { u.IsActive = val }

// GetCreatedAt will return the value of CreatedAt.
func (u *User) GetCreatedAt() *time.Time { return u.CreatedAt }

// SetCreatedAt sets CreatedAt to the provided value.
func (u *User) SetCreatedAt(stamp time.Time) { u.CreatedAt = &stamp }

// GetUpdatedAt will return the value of UpdatedAt.
func (u *User) GetUpdatedAt() *time.Time { return u.UpdatedAt }

// SetUpdatedAt sets UpdatedAt to the provided value.
func (u *User) SetUpdatedAt(stamp time.Time) { u.UpdatedAt = &stamp }

// GetDeletedAt will return the value of DeletedAt.
func (u *User) GetDeletedAt() *time.Time { return u.DeletedAt }

// SetDeletedAt sets DeletedAt to the provided value.
func (u *User) SetDeletedAt(stamp time.Time) { u.DeletedAt = &stamp }

// GetIsAgent will return the value of IsAgent.
func (u *User) GetIsAgent() bool { return u.IsAgent }

// SetIsAgent sets IsAgent to the provided value.
func (u *User) SetIsAgent(val bool) { u.IsAgent = val }

// UserTable is the name of the table in the DB.
const UserTable = "`user`"

// UserFields is a list of all columns in the DB table.
var UserFields = []string{"id", "email", "username", "full_name", "password", "is_admin", "is_active", "created_at", "updated_at", "deleted_at", "is_agent"}

// UserPrimaryFields are the primary key fields in the DB table.
var UserPrimaryFields = []string{"id"}

// Insert starts building an INSERT INTO query.
func (j *Job) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: JobTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := JobFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

// Select starts building a SELECT query.
func (j *Job) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: JobTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

// Update starts building a UPDATE query.
func (j *Job) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: JobTable}).Apply(opts...)
	cols := JobFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Delete starts building a DELETE query.
func (j *Job) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: JobTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Insert starts building an INSERT INTO query.
func (j *JobLog) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: JobLogTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := JobLogFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

// Select starts building a SELECT query.
func (j *JobLog) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: JobLogTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

// Update starts building a UPDATE query.
func (j *JobLog) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: JobLogTable}).Apply(opts...)
	cols := JobLogFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Delete starts building a DELETE query.
func (j *JobLog) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: JobLogTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Insert starts building an INSERT INTO query.
func (m *Migrations) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: MigrationsTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := MigrationsFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

// Select starts building a SELECT query.
func (m *Migrations) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: MigrationsTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

// Update starts building a UPDATE query.
func (m *Migrations) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: MigrationsTable}).Apply(opts...)
	cols := MigrationsFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Delete starts building a DELETE query.
func (m *Migrations) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: MigrationsTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Insert starts building an INSERT INTO query.
func (r *Repository) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: RepositoryTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := RepositoryFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

// Select starts building a SELECT query.
func (r *Repository) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: RepositoryTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

// Update starts building a UPDATE query.
func (r *Repository) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: RepositoryTable}).Apply(opts...)
	cols := RepositoryFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Delete starts building a DELETE query.
func (r *Repository) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: RepositoryTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Insert starts building an INSERT INTO query.
func (r *RepositoryRule) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: RepositoryRuleTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := RepositoryRuleFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

// Select starts building a SELECT query.
func (r *RepositoryRule) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: RepositoryRuleTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

// Update starts building a UPDATE query.
func (r *RepositoryRule) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: RepositoryRuleTable}).Apply(opts...)
	cols := RepositoryRuleFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Delete starts building a DELETE query.
func (r *RepositoryRule) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: RepositoryRuleTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Insert starts building an INSERT INTO query.
func (s *Session) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: SessionTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := SessionFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

// Select starts building a SELECT query.
func (s *Session) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: SessionTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

// Update starts building a UPDATE query.
func (s *Session) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: SessionTable}).Apply(opts...)
	cols := SessionFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Delete starts building a DELETE query.
func (s *Session) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: SessionTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Insert starts building an INSERT INTO query.
func (s *Setting) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: SettingTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := SettingFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

// Select starts building a SELECT query.
func (s *Setting) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: SettingTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

// Update starts building a UPDATE query.
func (s *Setting) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: SettingTable}).Apply(opts...)
	cols := SettingFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Delete starts building a DELETE query.
func (s *Setting) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: SettingTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Insert starts building an INSERT INTO query.
func (s *SSHKey) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: SSHKeyTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := SSHKeyFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

// Select starts building a SELECT query.
func (s *SSHKey) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: SSHKeyTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

// Update starts building a UPDATE query.
func (s *SSHKey) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: SSHKeyTable}).Apply(opts...)
	cols := SSHKeyFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Delete starts building a DELETE query.
func (s *SSHKey) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: SSHKeyTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Insert starts building an INSERT INTO query.
func (u *User) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := UserFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

// Select starts building a SELECT query.
func (u *User) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

// Update starts building a UPDATE query.
func (u *User) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserTable}).Apply(opts...)
	cols := UserFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Delete starts building a DELETE query.
func (u *User) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: UserTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}
