#!/usr/bin/env atkins
name: Release Atkins binaries

vars:
  semver: $(git tag | tail -n 1)
  build:
    goarch: [arm64, amd64]

jobs:
  default:
    steps:
      - passthru: true
        run: echo "Latest tag ${{semver}}"

  build:
    desc: "Build assets required for release"
    passthru: true
    steps:
      - task: build:docker

  build:docker:
    desc: "Build docker image"
    passthru: true
    steps:
      - docker buildx build --platform linux/amd64 -t titpetric/atkins:${{semver}} -t titpetric/atkins:latest -f docker/Dockerfile .

  test:
    desc: "Run tests required for release"
    passthru: true
    steps:
      - docker buildx build --platform linux/amd64 -t titpetric/atkins-test -f docker/Dockerfile.example .
      - docker run --rm titpetric/atkins-test -v $PWD/tests:/app -file nested.yml -l

  publish:
    desc: "Publish release assets"
    steps:
      - task: publish:github
      - task: publish:docker

  publish:github:
    desc: "Create a GitHub release"
    steps:
      - run: echo "Last release [${{semver}}]"
      - gh release create ${{ semver }} --title ${{semver}} --notes "Release ${{semver}}"
      - for: goarch in ${{build.goarch}}
        run: gh release upload ${{ semver }} ./bin/atkins-linux-${{goarch}}

  publish:docker:
    desc: "Push the Docker images"
    passthru: true
    steps:
      - docker push titpetric/atkins:latest
      - docker push titpetric/atkins:${{semver}}

